---
title: "Hello Blog in R"
subtitle: "This is a test"
summary: "This shows how to run lm, tidy the output and format it for publication"

author: "Ross Gilmour"
date: "2020-05-28"
slug: rmarkdown-lm-tidyr-kable
categories: 
  - R
  - Rmarkdown
tags:
  - Rmarkdown
  - kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, 
                      echo = TRUE, dpi = 300, cache.lazy = FALSE,
                      tidy = "styler", fig.width = 8, fig.height = 5)
```

## Fit the model

```{r cars}
lmfit <- lm(mpg ~ wt, mtcars)
lmfit
```

## Cleanup model output and format table

Use "broom"'s "tidy" function to create a data frame of the model output and output that dataframe using "knitr"'s "kable" function: 

```{r output}
library(broom)        # tidyr
library(magrittr)     # %>%

library(knitr)        # kable
library(kableExtra)   # kable_styling
mytable <- tidy(lmfit) %>% kable(format="latex",booktabs=TRUE,
                      caption="My table caption",digits=2) %>% 
                kable_styling(latex_options = "HOLD_position")
mytable
```
Add "longtable" to "kable" as required. For example: "kable(longtable=TRUE, format="latex", booktabs=TRUE, caption="My table caption")"
